### ISSUE TITLE
Missing src directory

### ISSUE THREAD

**Issue by CaptainGlac1er** [koajs/koa-router#13]
Should the src directory be reconstructed as I doubt the lib folder was the src directory (then ignore the new src fodler from npm with .npmignore [and possibly ignore the lib directory from github?]), and maybe use typescript as the base and transpile it for npm, and provide the typedef for people using typescript?

**Comment by dead-horse** [comment]
this project is a pure javascript project, and there is no src folder here, lib folder includes all the original code.
