### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by daerion** [koajs/koa-router#14]
As @jamesaspence mentioned in [his comment](https://github.com/ZijianHe/koa-router/issues/503#issuecomment-511053895) in an issue of the original repo - the [Koa Wiki](https://github.com/koajs/koa/wiki#routing-and-mounting) still points to the old repo and should be updated.

Creating an issue here to increase visibility and to make sure it doesn't slip off the radar.

**Comment by dead-horse** [comment]
the wiki is open to public and everyone can edit it.

**Comment by daerion** [comment]
I didn't even realize that :man_facepalming: 
Updated the wiki just now.
